# Generated by Django 5.2.4 on 2025-08-09 17:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField()),
                ('court_type', models.CharField(choices=[('High', 'High Court'), ('District', 'District Court'), ('Supreme', 'Supreme Court')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=100)),
                ('case_number', models.CharField(max_length=100)),
                ('filing_year', models.IntegerField()),
                ('query_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CAPTCHA_REQUIRED', 'CAPTCHA Required'), ('NOT_FOUND', 'Case Not Found')], default='SUCCESS', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_case_queries', to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_case_queries', to='cases.court')),
            ],
            options={
                'ordering': ['-query_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CaseMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petitioner', models.TextField(blank=True)),
                ('respondent', models.TextField(blank=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('case_status', models.CharField(blank=True, max_length=100)),
                ('judge', models.CharField(blank=True, max_length=200)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='cases.casequery')),
            ],
        ),
        migrations.CreateModel(
            name='OrderJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('ORDER', 'Order'), ('JUDGMENT', 'Judgment'), ('NOTICE', 'Notice'), ('OTHER', 'Other')], max_length=50)),
                ('pdf_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_latest', models.BooleanField(default=False)),
                ('case_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cases.casemetadata')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
    ]
